# Generated by Django 3.1 on 2020-08-24 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.BooleanField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('category', models.CharField(max_length=60)),
            ],
        ),
    ]
