# Generated by Django 3.1.1 on 2020-09-03 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='owner',
        ),
    ]
